"""Network element configuration for HAEO integration.

The Network element represents the main AC bus (electrical network) that other
elements connect to. It serves as the central connection point for:
- Inverters (DC to AC conversion)
- Grids (utility connection)
- Loads (consumption points)

The Network creates a SourceSink node in the model that acts as a junction point
without being a source or sink itself - power flows through it between connected elements.

Additionally, the network device outputs hub-level optimization results:
- Optimization cost
- Optimization status
- Optimization duration
"""

from collections.abc import Mapping
from typing import Any, Final, Literal, TypedDict

from custom_components.haeo.model import ModelOutputName
from custom_components.haeo.model.output_data import OutputData
from custom_components.haeo.model.source_sink import SOURCE_SINK_POWER_BALANCE
from custom_components.haeo.schema.fields import NameFieldData, NameFieldSchema

ELEMENT_TYPE: Final = "network"

# Network element output (from model)
type NetworkElementOutputName = Literal["network_power_balance"]

NETWORK_ELEMENT_OUTPUT_NAMES: Final[frozenset[NetworkElementOutputName]] = frozenset(
    (NETWORK_POWER_BALANCE := "network_power_balance",)
)

# Hub-level optimization outputs (not from model, generated by coordinator)
type NetworkHubOutputName = Literal[
    "network_optimization_cost",
    "network_optimization_status",
    "network_optimization_duration",
]

NETWORK_HUB_OUTPUT_NAMES: Final[frozenset[NetworkHubOutputName]] = frozenset(
    (
        OUTPUT_NAME_OPTIMIZATION_COST := "network_optimization_cost",
        OUTPUT_NAME_OPTIMIZATION_STATUS := "network_optimization_status",
        OUTPUT_NAME_OPTIMIZATION_DURATION := "network_optimization_duration",
    )
)

# Combined output names for the network device
type NetworkOutputName = NetworkElementOutputName | NetworkHubOutputName

NETWORK_OUTPUT_NAMES: Final[frozenset[NetworkOutputName]] = frozenset(
    NETWORK_ELEMENT_OUTPUT_NAMES | NETWORK_HUB_OUTPUT_NAMES
)

type NetworkDeviceName = Literal["network"]

NETWORK_DEVICE_NAMES: Final[frozenset[NetworkDeviceName]] = frozenset(
    (NETWORK_DEVICE := ELEMENT_TYPE,),
)


class NetworkConfigSchema(TypedDict):
    """Network element configuration."""

    element_type: Literal["network"]
    name: NameFieldSchema


class NetworkConfigData(TypedDict):
    """Network element configuration."""

    element_type: Literal["network"]
    name: NameFieldData


CONFIG_DEFAULTS: dict[str, Any] = {}


def create_model_elements(config: NetworkConfigData) -> list[dict[str, Any]]:
    """Create model elements for Network configuration.

    Creates a SourceSink node that serves as the central AC bus junction point.
    It's neither a source nor a sink - power flows through it between connected elements.
    """
    return [
        {
            "element_type": "source_sink",
            "name": config["name"],
            "is_source": False,
            "is_sink": False,
        },
    ]


def outputs(
    name: str, model_outputs: Mapping[str, Mapping[ModelOutputName, OutputData]], _config: NetworkConfigData
) -> Mapping[NetworkDeviceName, Mapping[NetworkOutputName, OutputData]]:
    """Map model outputs to network-specific output names."""
    network_node = model_outputs[name]

    network_outputs: dict[NetworkOutputName, OutputData] = {}

    # Power balance shadow price from the SourceSink node
    network_outputs[NETWORK_POWER_BALANCE] = network_node[SOURCE_SINK_POWER_BALANCE]

    return {NETWORK_DEVICE: network_outputs}


__all__ = [
    "CONFIG_DEFAULTS",
    "ELEMENT_TYPE",
    "NETWORK_DEVICE_NAMES",
    "NETWORK_ELEMENT_OUTPUT_NAMES",
    "NETWORK_HUB_OUTPUT_NAMES",
    "NETWORK_OUTPUT_NAMES",
    "NETWORK_POWER_BALANCE",
    "NetworkConfigData",
    "NetworkConfigSchema",
    "NetworkDeviceName",
    "NetworkElementOutputName",
    "NetworkHubOutputName",
    "NetworkOutputName",
    "OUTPUT_NAME_OPTIMIZATION_COST",
    "OUTPUT_NAME_OPTIMIZATION_DURATION",
    "OUTPUT_NAME_OPTIMIZATION_STATUS",
    "create_model_elements",
    "outputs",
]
